layout_spectrum: 1
typography_spectrum: 0.1391231
color:
  lightness: 0.5623946
  brandStrength: 0.6669477
  saturation: 0.08858758
  rhythmicContrast: 1
  brandColors:
    - '#000101'
    - '#0083F5'
    - '#FD57C9'
    - '#D4F0F7'
    - '#F10092'
name: Butterfly Babysitting
